server:
  port: 8010

spring:
  profiles:
    active: dev
  application:
    name: osir-springai
  ai:
    ollama:
      base-url: ${ai.ollama.base-url}
      chat:
        options:
          model: ${ai.ollama.model}
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${ai.openai.base-url}
      chat:
        options:
          model: ${ai.openai.model}



  datasource:
    driver-class-name: ${mysql.datasource.driver-class-name}
    url: jdbc:mysql://${mysql.datasource.host}:${mysql.datasource.port}/${mysql.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mysql.datasource.username}
    password: ${mysql.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osir.springai.entity
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.osir.springai: debug